config/routes.rb
Rails.application.routes.draw do

  # USERS & ADMINISTRATION
  devise_for :admins
  devise_for :users,
             :skip => [:registrations]
  as :user do
    get 'users/edit'  => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users'       => 'users/registrations#update', :as => 'user_registration'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # HOME
  root to: 'home#index'
  
  
  # RESSOURCES
  resources :commercials, path: 'commerciaux'
  resources :projects,    path: 'projets'
  resources :payments#,    path: 'paiement'
  resources :purchases,   path: 'achats'
  resources :suppliers,   path: 'fournisseurs'
  resources :customers,   path: 'clients'
  resources :orders,      path: 'commande'
  resources :quotes,      path: 'devis'
  resources :articles
  resources :order_items
  resources :units
  resources :conceptions, path: 'be'
  resources :house_modules, path: 'modules'
  resources :products, path: 'produits'

  get '/order/:order/item/new', to: 'order_items#new', as: 'new_order_item_supplier'

  # PAGE
  get '/pages/:id' => 'pages#show', as: 'page'

  # DESTROY LINKS
  resources :order_items, only: :destroy
  resources :articles_suppliers, only: :destroy

  # FROALA (WYSIWYG
  post '/froala_upload' => 'froala#upload'
  post '/froala_manage' => 'froala#manage'
  delete '/froala_delete' => 'froala#delete'
end

app/models/quote.rb
# == Schema Information
#
# Table name: quotes
#
#  id         :integer          not null, primary key
#  project_id :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  deleted_at :datetime
#  draft?     :boolean          default(TRUE)
#  product_id :integer
#
# Indexes
#
#  index_quotes_on_product_id  (product_id)
#  index_quotes_on_project_id  (project_id)
#  index_quotes_on_user_id     (user_id)
#

class Quote < ActiveRecord::Base
  before_create :set_quote_on_create
  before_update :update_construction_state
  before_destroy :check_if_draft

  default_scope { where(deleted_at: nil) }
  
  belongs_to :project
  belongs_to :user
  belongs_to :product
  has_and_belongs_to_many :construction_states
  has_and_belongs_to_many :quote_states

  # validates_presence_of :user
  #validates :project_id, presence: true, uniqueness: {scope: :user_id}
  
  def to_label
    "Devis n°#{id}"
  end
  
  def last_updated_at
      times = []
      times << self.updated_at
      times << self.quote_states.last.updated_at unless self.quote_states.last.nil?
      times << self.construction_states.last.updated_at unless self.construction_states.last.nil?
      
      return times.max
  end

  private

    def set_quote_on_create
      if User.current.nil?
        self.user = User.find_by(email: "commercial@madera.com") unless self.user.nil?
      else
        self.user = User.current
      end
      self.quote_states<< QuoteState.find_by_name(:brouillon)
    end

    def update_construction_state
      if quote_states.last == QuoteState.find_by_name('accepté')
        construction_states<<ConstructionState.find_by_name('Devis signé')
      end
    end

    def check_if_draft
      return true if self.quote_states.last != QuoteState.find_by_name(:brouillon)
      errors.add(:quote_states, 'Seul les devis à l\'état de brouillon sont effacable')
      false
    end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  load_and_authorize_resource
  add_breadcrumb "Devis", :quotes_path

  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.order('updated_at DESC')
    @quotes = @quotes.page(params[:page])
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    add_breadcrumb "Devis n°" + @quote.id.to_s
    @product = @quote.product
    @modules = @product.house_modules
    respond_to do |format|
      format.html
      format.json
      format.pdf do
        if @quote.quote_states.last == QuoteState.find_by_name('brouillon')
          @quote.update(
              quote_states: @quote.quote_states<< QuoteState.find_by_name('en attente')
          )
        end
        @down_payment = ConstructionState.find_by_name('Devis signé').value * 100
            render pdf: "commande_#{@quote.id}",
               show_as_html: params.key?('debug'),
               footer: {
                   right: 'page [page]/[topage]',
                   center: "Devis n° #{@quote.id}",
                   left: "Édité le #{Time.now.strftime('%d-%m-%Y')}"
               }
      end
    end
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
    @default_products = Product.draft_or_default
    add_breadcrumb "Nouveau Devis"
  end

  # GET /quotes/1/edit
  def edit
    add_breadcrumb "Editer devis n°#{@quote.id}"
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Le devis a été créé avec succès.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    if params.key?(:status)
# <<<<<<< HEAD
        @quote.update(quote_states: @quote.quote_states<<QuoteState.find_by_name('accepté')) if params[:status][:accept]
        @quote.quote_states<<QuoteState.find_by_name('refusé') if params[:status][:decline]
        redirect_to @quote, notice: "L'état du devis à été mis à jour"
=begin

=======
      @quote.quote_states << QuoteState.find_by_name('refusé') if params[:status][:decline]
      redirect_to @quote, notice: "L'état du devis à été mis à jour"



      # GENERATION DE COMMANDES
      if params[:status][:accept]
        listSuppliers = Hash.new
        modules = @quote.product.house_modules
        
        modules.each do |m|
          m.articles.each do |a|
            
            art = ArticlesSupplier.where(article: a.id).order(:price).first
            listSuppliers[art.supplier] = [] if listSuppliers[art.supplier].nil?
            listSuppliers[art.supplier] << art
            
          end
        end
        
        listSuppliers.each do |supplier,artsup_array|
          q = Order.create!(supplier: supplier, quote: @quote, effective?: true)  
          
          artsup_array.each do |art_sup|
            OrderItem.create!(articles_supplier: art_sup,
                             order: q,
                              quantity: 1) # hmpf
          end
        end
      end

>>>>>>> anthony

=end
    else
      respond_to do |format|
        if @quote.update(quote_params)
          format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
          format.json { render :show, status: :ok, location: @quote }
        else
          format.html { render :edit }
          format.json { render json: @quote.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    respond_to do |format|
      if @quote.destroy
        format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:project_id, :product_id, :quote_state_ids, :construction_state_ids)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper

  def quote_buttons quote
    output = '<div class="change-states-forms">'
    if quote.quote_states.last == QuoteState.find_by_name('brouillon')
      output += '<a href="'+quote_path(quote, format: :pdf)+'" target="_blank" class="btn btn-primary">'
      output += '  <span class="glyphicon glyphicon glyphicon-print" aria-hidden="true"> </span>'
      output += '  Valider'
      output += '</a> '
      output += '<a href="'+edit_quote_path+'" class="btn btn-primary">'
      output += '  <span class="glyphicon glyphicon-edit" aria-hidden="true"> </span>'
      output += '  Editer'
      output += '</a>'
      output += <<-HTML
                <button class="btn-danger" data-toggle="modal" data-target="#delete">
                  <span class="glyphicon glyphicon-remove" aria-hidden="true"> </span>
                  Supprimer
                </button>
      HTML
      return raw(output)
    end
    if quote.quote_states.last == QuoteState.find_by_name('en attente')
      output += render('accept_or_decline')
    end

    output += '<a href="'+quote_path(quote, format: :pdf)+'" target="_blank" class="btn btn-default">' #, format: :pdf
    output += '  <span class="glyphicon glyphicon glyphicon-print" aria-hidden="true"> </span>'
    output += '  Imprimer'
    output += '</a>'
    output += '</div>'
    raw(output)
  end

end

app/views/quotes/_accept_or_decline.html.erb
<%= simple_form_for(@quote) do |f| %>
    <%= hidden_field :status, :accept, value: true %>
    <%= f.submit 'Accepter le devis' %>
<% end %>
<%= simple_form_for(@quote) do |f| %>
    <%= hidden_field :status, :decline, value: true %>
    <%= f.submit 'Refuser le devis' %>
<% end %>

app/views/quotes/_detail.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Détail du devis
  </div>
  <div class="panel-body">
    <table class="table table-hover table-condensed">
      <thead>
        <tr>
          <th><%= 'Nom' %></th>
          <th><%= 'Référence' %></th>
          <th><%= 'Description' %></th>
          <th><%= 'Prix HT' %></th>
          <th><%= 'Prix TTC' %></th>
          <th></th>
        </tr>
      </thead>
      
      <tbody>
        <% @modules.each_with_index do |m,i| %>
          <tr class="info">
            <td><%= "#{i+1} | #{m.name}" %></td>
            <td></td>
            <td><%= truncate(m.description) %></td>
            <td><%= number_to_currency(m.module_price, locale: :fr) %></td>
            <td><%= number_to_currency(m.module_price_w_vat, locale: :fr) %></td>
            <td class="text-right">
              <%= link_to(
                raw('<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>'), m)
              %>
            </td>
          </tr>
          
          <% m.articles.each do |a| %>
            <tr>
                <td><%= a.name %></td>
                <td><%= a.reference %></td>
                <td><%= truncate(a.description) %></td>
                <td><%= number_to_currency(a.lowest_price, locale: :fr) %></td>
                <td><%= number_to_currency(a.lowest_price_w_vat, locale: :fr) %></td>
                <td class="text-right">
                  <%= link_to(
                    raw('<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>'), a)
                  %>
                </td>
            </tr>
          <% end %>
        <% end %>
          <tfoot>
              <td></td>
              <td></td>
              <td>Total</td>
              <td><%= number_to_currency(@product.product_price, locale: :fr) %></td>
              <td><%= number_to_currency(@product.product_price_w_vat, locale: :fr) %></td>
              <td></td>
          </tfoot>
      </tbody>
    </table>
  </div>
</div>

app/views/quotes/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= simple_form_for(@quote,  wrapper: :horizontal_form) do |f| %>
      <%= f.error_notification %>
      <div class="form-horizontal">
        <div class="form-inputs">
          <% if action == :new %>
              <%= f.association :project,
                                label: t('project').titleize,
                                selected: params[:project] %>
          <% end %>
          <% if action == :edit %>
              <%= f.input :projet,
                          as: :fake,
                          disabled: true,
                          input_html: {value: @quote.project.to_label } %>
          <% end %>
          <%# if action == :edit %>
              <%#= f.input 'Avancement du chantier',
                          as: :fake,
                          disabled: true,
                          input_html: {
                              value: @quote.construction_states.empty? ? 'Non commencé' : @quote.construction_states.last.name
                          } %>
<!--
              <div class="form-group">
                <label class="col-sm-3 control-label" for="quote_quote_states">Statut du devis</label>
                <div class="col-sm-9">
                  <%#= f.collection_select :quote_state_ids, QuoteState.all, :id, :name, class: 'form-control' %>
                </div>
              </div>
-->
          <%# end %>
          <%= f.association :product,
                            collection: Product.draft_or_default,
                            selected: @quote.product.present? ? @quote.product.id : params[:select_product] ,
                            include_blank: false %>
        </div>
        <hr>
        <div id="product-show"></div>
        <hr>
        <div class="form-actions">
          <%
            btn_label = 'ok'
            btn_label = 'Mettre à jour le devis' if action == :edit
            btn_label = 'Créer avec ce produit' if action == :new
          %>
          <%= f.submit btn_label %>
          <a href="#" class="btn btn-default" id="new-product">Créer un nouveau produit à partir de celui ci</a>
          <%= link_to('Retour', quotes_path, class: 'btn btn-default pull-right') %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script>
    var $productSelect = $('#quote_product_id');

    // Show du product
    function loadProductShow() {
        var selectId = $productSelect.val();
        console.log('Charge le produit '+selectId)
        $.ajax({
            url: '<%= products_path%>/'+selectId,
            dataType: 'script'
        });
    }
    $productSelect.on('change', loadProductShow);
    loadProductShow();

    // Création d'une copie du product selectionner
    $('#new-product').on('click', function(e){
        e.preventDefault();
        var selectId = $productSelect.val();
        document.location = '<%= new_product_path %>?product_model_id='+selectId;
    })
</script>

app/views/quotes/_products.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Produits correspondants
  </div>
  <div class="panel-body">
    <table>
      <thead>
        <tr>
          <th><%= 'Nom' %></th>
          <th><%= 'Descriptif' %></th>
          <th><%= 'Ref. CCTP' %></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
          <tr>
            <td><%= "#{@product.id} |  #{@product.name}" %></td>
            <td><%= truncate(@product.descriptif) %></td>
            <td><%= @product.cctp_reference %></td>
            <td class="text-right">
              <%= link_to(
                raw('<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>'),
                @product
                )
              %>
            </td>
          </tr>
      </tbody>
    </table>
    <%#= link_to 'Ajouter un devis au projet', new_quote_path(project: @project), class: 'btn btn-primary' %>
  </div>
</div>

app/views/quotes/edit.html.erb
<% provide(:title, t('quote')) %>
<% provide(:subtitle, 'Edition') %>

<%= render 'form', action: :edit %>

app/views/quotes/index.html.erb
<% provide(:title, t('quote')) %>
<% provide(:subtitle, 'Liste') %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title"><%= t('listing quotes').titleize %></h2>
  </div>
  <div class="panel-body">
    <table>
      <thead>
        <tr>
              <th><%= t('project').titleize %></th>
              <th><%= t('user').titleize %></th>
              <th><%= 'Etat du devis' %></th>
              <th><%= 'Etat du chantier' %></th>
              <th><%= 'Mise à jour' %></th>
              <th></th>
        </tr>
      </thead>

      <tbody>
        <% @quotes.each do |quote| %>
          <tr>
                <td><%= "#{quote.project.id} |  #{quote.project.customer.fullname if quote.project.customer.present? }" %></td>
                <td><%= quote.user.display_fullname if quote.user.present? %></td>
                <td><%= quote.quote_states.last.name %></td>
                <td><%= quote.construction_states.last.name unless quote.construction_states.last.nil? %></td>
                <td><%= format_date(quote.last_updated_at) %></td>
                <td class="text-right">
                  <%= link_to(
                    raw('<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>'),
                    quote
                  )
                  %>
                  |
                  <%= link_to(
                    raw('<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>'),
                    edit_quote_path(quote)
                  )
                  %>
                </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% if @quotes.total_pages > 1 %>
      <nav aria-label="Page navigation" class="text-center">
        <%= paginate @quotes, window: 1, outer_window: 1 %>
      </nav>
    <% end %>

    <br>

    <%= link_to "Nouveau #{t('quote')}", new_quote_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/quotes/new.html.erb
<% provide(:title, t('quote')) %>
<% provide(:subtitle, 'Création') %>

<%= render 'form', action: :new %>

app/views/quotes/show.html.erb
<% provide(:title, t('quote')) %>
<% provide(:subtitle, 'Création') %>


<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="Effacer">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Êtes vous certain ?</h4>
      </div>
      <div class="modal-body">
        Êtes vous certain de vouloir effacer cet élément ?
      </div>
      <div class="modal-footer">
        <%= link_to 'Effacer',  @quote,  method: :delete, class: 'btn btn-danger' %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
      </div>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <%= simple_form_for(@quote,  wrapper: :horizontal_form) do |f| %>
        <%= f.error_notification %>
        <div class="form-horizontal">
          <div class="form-inputs">
            <%= f.association :project,
                              label: t('project').titleize,
                              selected: params[:project],
                              input_html: { disabled: true } %>
          </div>
          <div class="form-inputs">
            <% state = @quote.quote_states.last %>
            <%= f.input :user,
                        label: 'Commercial',
                        as: :fake,
                        input_html: {
                            disabled: true,
                            value: (@quote.user.display_fullname if @quote.user.present?)
                        }
            %>
            <%= f.input :state,
                        label: 'État du devis',
                        as: :fake,
                        input_html: {
                            disabled: true,
                            value: @quote.quote_states.last.name
                        }
            %>
            <% construction_state = @quote.construction_states.last %>
            <%= f.input :construction_state,
                        label: 'Avancement des travaux',
                        as: :fake,
                        input_html: {
                            disabled: true,
                            value: construction_state ? construction_state.name : 'Non commencé'
                        }
            %>
          </div>
          <div class="form-actions">
            <%= link_to('Retour', :back, class: 'btn btn-default pull-right') %>
          </div>
        </div>
    <% end %>
    <%= quote_buttons(@quote) %>
  </div>
</div>


<%= render 'products', action: :show unless @product.nil? %>
<%= render 'detail', action: :show unless @product.nil? %>

app/views/quotes/show.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8'/>
    <%= wicked_pdf_stylesheet_link_tag 'pdf/quote' %>
  </head>
  <body id="pdf">

    <header>

      <div class="clearfix">

        <div class="madera-details">
          <%= wicked_pdf_image_tag 'main_app_logo' %>
          <h2>Madera</h2>
          <address>
            Adresse
            <div class="phone">00 00 00 00</div>
            <div class="fax">00 00 00 00</div>
            <div class="siret">11111111111111111</div>
            <div class="mail"><%= @quote.user.email %></div>
          </address>
        </div>

         <div class="order-details">
          <div class="form-group">
      à      <label><h2>Date </h2></label>
            <input
              type="text"
              value="<%= @quote.quote_states.last.created_at.strftime('%d/%m/%Y') %>"
            >
          </div>
          <div class="form-group">
            <label><h2>Projet n°</h2></label>
            <input type="text" value="<%= @quote.project.id %>">
          </div>
        </div>
      </div>

      <div class="clearfix">
        <hr>
        <h1>Devis n°<%= @quote.id %></h1>
        <div class="to">
          <div class="form-group">
            <label>Nom</label>
            <input type="text" value="<%= @quote.project.customer.fullname %>">
          </div>
          <div class="form-group">
            <label>Tel</label>
            <input type="text" value="<%= @quote.project.customer.phone_number %>">
          </div>
          <div class="form-group">
            <label>Adresse</label>
            <textarea><%= @quote.project.customer.address %></textarea>
          </div>
        </div>
      </div>
    </header>
    <hr>

    <div class="spacer"></div>

    <table>
      <thead>
        <tr>
          <th class="ref">Réf</th>
          <th class="description">Nom</th>
          <th class="description">Description</th>
          <th class="price">Prix HT</th>
          <th class="total">Prix TTC</th>
        </tr>
      </thead>
      <tbody>
        <% @quote.product.house_modules.each do |hm| %>
          <tr>
            <td>M<%= hm.id %></td>
            <td><%= hm.name %></td>
            <td><%= hm.description %></td>
            <td style="text-align: right"><%= number_to_currency(hm.module_price, locale: :fr) %></td>
            <td style="text-align: right"><%= number_to_currency(hm.module_price_w_vat, locale: :fr) %></td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td></td>
          <td></td>
          <td style="text-align: right">Total</td>
          <td style="text-align: right"><%= number_to_currency(@quote.product.product_price, locale: :fr) %></td>
          <td style="text-align: right"><%= number_to_currency(@quote.product.product_price_w_vat, locale: :fr) %></td>
        </tr>
      </tfoot>

    </table>

    <div class="spacer"></div>

    <div class="clearfix">
      <hr>
      <div class="validation-box">
        <div class="form-group">
          <label>Bon pour accord le </label>
          <input type="text">
        </div>
        <div class="form-group">
          <label>Signature </label>
          <textarea></textarea>
        </div>
      </div>
      <p class="down-payment">
        A la validation du devis, un accompte de <%= number_to_percentage(@down_payment) %> vous sera demandé,<br>
        soit <%= number_to_currency(@quote.product.product_price_w_vat * @down_payment, locale: :fr) %> TTC.
      </p>
    </div>
    <hr>
  </body>
</html>