config/routes.rb
Rails.application.routes.draw do

  # USERS & ADMINISTRATION
  devise_for :admins
  devise_for :users,
             :skip => [:registrations]
  as :user do
    get 'users/edit'  => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users'       => 'users/registrations#update', :as => 'user_registration'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # HOME
  root to: 'home#index'
  
  
  # RESSOURCES
  resources :commercials, path: 'commerciaux'
  resources :projects,    path: 'projets'
  resources :payments#,    path: 'paiement'
  resources :purchases,   path: 'achats'
  resources :suppliers,   path: 'fournisseurs'
  resources :customers,   path: 'clients'
  resources :orders,      path: 'commande'
  resources :quotes,      path: 'devis'
  resources :articles
  resources :order_items
  resources :units
  resources :conceptions, path: 'be'
  resources :house_modules, path: 'modules'
  resources :products, path: 'produits'

  get '/order/:order/item/new', to: 'order_items#new', as: 'new_order_item_supplier'

  # PAGE
  get '/pages/:id' => 'pages#show', as: 'page'

  # DESTROY LINKS
  resources :order_items, only: :destroy
  resources :articles_suppliers, only: :destroy

  # FROALA (WYSIWYG
  post '/froala_upload' => 'froala#upload'
  post '/froala_manage' => 'froala#manage'
  delete '/froala_delete' => 'froala#delete'
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id                 :integer          not null, primary key
#  name               :string
#  article_group_id   :integer
#  value_added_tax_id :integer
#  reference          :string
#  description        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  deleted_at         :datetime
#
# Indexes
#
#  index_articles_on_article_group_id    (article_group_id)
#  index_articles_on_value_added_tax_id  (value_added_tax_id)
#

class Article < ActiveRecord::Base

  default_scope { where(deleted_at: nil) }
  
  belongs_to :article_group
  belongs_to :value_added_tax
  has_many :articles_units

  has_many :articles_suppliers
  has_many :suppliers, through: :articles_suppliers
  
  has_many :articles_modules
  has_many :house_modules, through: :articles_modules
  
  accepts_nested_attributes_for :articles_suppliers
  accepts_nested_attributes_for :articles_units

  validates_presence_of :value_added_tax,
                        :name,
                        :reference,
                        :article_group#,
                        # :suppliers

  def lowest_price
    self.articles_suppliers.order('price').first.price
  end
  
  def lowest_price_w_vat
    price = self.articles_suppliers.order('price').first.price
    price = price + ( price * (self.value_added_tax.value / 100) )
    return price
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource
  add_breadcrumb "Articles", :articles_path

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index

    @articles =  Article.all
    @articles = @articles.where('name LIKE ?', '%'+params[:nom]+'%') if !params[:nom].blank?
    @articles = @articles.where('reference LIKE ?', '%'+params[:ref]+'%') if !params[:ref].blank?
    @articles = @articles.page(params[:page])

  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    add_breadcrumb @article.name
    @suppliers=Article.find(@article.id).suppliers
  end

  # GET /articles/new
  def new
    @article = Article.new
    @units = Unit.where(unit_category_id: 1 )
    add_breadcrumb "Nouvel Article"
  end

  # GET /articles/1/edit
  def edit
    add_breadcrumb "Editer " + @article.name
    @suppliers=Article.find(@article.id).suppliers
    @article_unit = @article.articles_units.first
    @unit = @article_unit.unit
    @units = Unit.where(unit_category: @unit.unit_category )

  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        @article_unit = ArticlesUnit.create(article: @article,
                                            unit_id: params[:articles_units][:unit_id],
                                            value: params[:articles_units][:value])
        format.html { redirect_to @article, notice: "L'Article a été créé avec succès." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        @article.articles_units.last.update(unit_id: params[:articles_units][:unit_id],
                                       value: params[:articles_units][:value])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name,
                                      :article_group_id,
                                      :value_added_tax_id,
                                      :reference,
                                      :description,
                                      supplier_ids: []
                                      #articles_units_attributes: [:unit_id, :value]
      )

    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def show_or_count_supplier_in_article art_id
    a = Article.find(art_id).suppliers
    ac = Article.find(art_id).articles_suppliers.order(price: :asc)
    c = a.count
    
    if c > 1 then
      minpriced = a.find_by(id: ac.first.supplier_id)
      
      return "#{minpriced.name} [+#{c-1}...]"
    elsif c == 1
      return a.first.name
    else
      return 'Aucun fournisseur'
    end
    
  end
end

app/views/articles/_articles_supplier.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Fournisseurs correspondants
  </div>
  <div class="panel-body">
    <table>
      <thead>
        <tr>
          <th><%= t('name').titleize %></th>
          <th><%= 'Reference' %></th>
          <th><%= 'Prix HT' %></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @suppliers.each do |ac| %>
          <% as = ac.articles_suppliers.where(supplier_id: ac.id, article_id: @article.id).first %>
          <tr>
            <td><%= "#{ac.id} | #{ac.name}" %></td>
            <td><%= as.supplier_reference %></td>
            <td><%= number_to_currency(as.price, locale: :fr) %></td>
            <td class="text-right">
              <%= link_to(
                raw('<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>'),
                ac
              ) %>
              <% if action == :edit %>
                |
                <%= link_to(
                  raw('<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>'),
                  "#", data: { confirm: 'Non fonctionnel : Edition de la ref et prix' }
                )
                %>
                |
                <%= link_to(
                  raw('<span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>'),
                  articles_supplier_path,
                  method: :delete,
                  data: { confirm: "Suppression de l'article fournisseur, souhaitez vous continuer?" }
                ) %>
              <% end %>

            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/articles/_form.html.erb
<%= simple_form_for(@article,  wrapper: :horizontal_form) do |f| %>
  <%= f.error_notification %>
  <div class="form-horizontal">
    <div class="form-inputs">
      <% disabled = (action == :show) ? true : false %>
      <%= f.input :name, input_html: { disabled: disabled } %>
      <%= f.association :article_group, label: t('article_group').titleize, input_html: { disabled: disabled } %>
      <%= f.association :value_added_tax, label: 'TVA', input_html: { disabled: disabled } %>
      <%= f.input :reference, input_html: { disabled: disabled } %>
      <%= f.input :description, input_html: { disabled: disabled } %>
      <%= f.association :suppliers, collection: Supplier.order('name ASC'), label: 'Fournisseur' %>
      <%= f.input :unit_category,
                  as: :fake_select,
                  collection: UnitCategory.all,
                  selected: "#{@unit.nil? ? UnitCategory.first : @unit.unit_category.id }",
                  label: "Catégorie d'unité",
                  input_html: {
                      'data-remote': true,
                      'data-url': units_path,
                      format: :json
                  }
      %>
      <%#= simple_fields_for 'articles_units_attributes[]', @article_unit, wrapper: :horizontal_form do |au| %>
      <%= simple_fields_for 'articles_units', wrapper: :horizontal_form do |au| %>
        <%= au.input  :unit_id,
                      collection: @units,
                      selected: @unit,
                      label: 'Unité'
        %>
        <%= au.input :value, input_html: {value: "#{@article_unit ? @article_unit.value : ''}" } %>
      <% end %>
    </div>
    
    <div class="form-actions">
      <% if action == :new %>
          <%= f.submit 'Créer' %>
      <% end %>
      <% if action == :edit %>
          <%= f.submit 'Mettre à jour' %>
      <% end %>
      <%= link_to('Retour', articles_path, class: 'btn btn-default pull-right') %>
    </div>
  </div>
<% end %>

app/views/articles/_select_units.html.erb
<%= @units.each do |u| %>
    <option value="<%= u.id %>"><%= u.name %></option>
<% end %>

app/views/articles/edit.html.erb
<% provide(:title, t('article')) %>
<% provide(:subtitle, 'Edition') %>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form', action: :edit %>
  </div>
</div>

<%= render 'articles_supplier', action: :edit %>

app/views/articles/index.html.erb
<% provide(:title, t('article')) %>
<% provide(:subtitle, 'Liste') %>

<div class="panel panel-default">
  
  
  <div class="panel-heading">
    <div class="row">
      <div class="col-sm-4">
        <h2 class="panel-title"><%= t('listing articles').titleize %></h2>
      </div>
      <div class="col-sm-8">
        <%= form_tag(articles_path, method: "get", class: 'form-inline pull-right') do %>
            <%= label_tag(:nom, "Filtrer les résultats : ") %>
            <%= text_field_tag(:nom, value = params[:nom], :placeholder => "Nom") %>
            <%= text_field_tag(:ref, value = params[:ref], :placeholder => "Référence") %>
            <%= submit_tag("Filtrer", name: nil) %>
        <% end %>
      </div>
    </div>

  </div>
  
  <div class="panel-body">
    <table>
      <thead>
        <tr>
              <th><%= t('name').titleize %></th>
              <th><%= 'Reference' %></th>
              <th><%= t('description').titleize %></th>
              <th><%= 'Type' %></th>
              <th><%= 'Fournisseur' %></th>
              <th></th>
        </tr>
      </thead>

      <tbody>
        <% @articles.each do |article| %>
          <tr>
                <td><%= article.name %></td>
                <td><%= article.reference %></td>
                <td><%= truncate(article.description) %></td>
                <td><%= article.article_group.name %></td>
                <td><%= show_or_count_supplier_in_article(article.id) %></td>
                <td class="text-right">
              <%= link_to(
                raw('<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>'),
                article
              ) %>
              |
              <%= link_to(
                raw('<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>'),
                edit_article_path(article)
              ) %>
              |
              <%= link_to(
                raw('<span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>'),
                article,
                method: :delete, data: { confirm: 'Êtes vous certain ?' }
              ) %>

            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% if @articles.total_pages > 1 %>
      <nav aria-label="Page navigation" class="text-center">
        <%= paginate @articles, window: 1, outer_window: 1 %>
      </nav>
    <% end %>

    <br>

    <%= link_to "Nouvel #{t('article')}", new_article_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/articles/new.html.erb
<% provide(:title, t('Article')) %>
<% provide(:subtitle, 'Création') %>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form', action: :new %>
  </div>
</div>

app/views/articles/show.html.erb
<% provide(:title, t('article')) %>
<% provide(:subtitle, 'Création') %>


<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="Effacer">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Êtes vous certain ?</h4>
      </div>
      <div class="modal-body">
        Êtes vous certain de vouloir effacer cet élément ?
      </div>
      <div class="modal-footer">
        <%= link_to 'Effacer', @article, method: :delete, class: 'btn btn-danger' %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
      </div>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-body">

    <div class="form-horizontal">
      <div class="form-inputs">
        <div class="form-group">
          <label class="col-sm-3 control-label" for="article_name">Nom *</label>
          <div class="col-sm-9">
            <input class="form-control" aria-required="true" type="text" id="article_name" value="<%= @article.name %>" disabled>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label" for="article_article_group_id">Type D'article *</label>
          <div class="col-sm-9">
            <input class="form-control" aria-required="true" type="text" id="article_article_group_id" value="<%= @article.article_group.name %>" disabled>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label" for="article_value_added_tax_id">TVA *</label>
          <div class="col-sm-9">
            <input class="form-control"
                   aria-required="true"
                   type="text"
                   id="article_value_added_tax_id"
                   value="<%= @article.value_added_tax.to_label %>"
                   disabled>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label" for="article_fournisseur">Fournisseurs *</label>
          <div class="col-sm-9">
            <input class="form-control"
                   aria-required="true"
                   type="text"
                   id="article_value_added_tax_id"
                   value="<%= @article.suppliers.pluck(:name).join(', ') %>"
                   disabled>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label" for="article_reference">Reference *</label>
          <div class="col-sm-9">
            <input class="form-control"
                   aria-required="true"
                   type="text"
                   id="article_value_added_tax_id"
                   value="<%= @article.reference %>"
                   disabled>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label" for="article_description">Description</label>
          <div class="col-sm-9">
            <textarea class="form-control text optional"
                      name="article[description]"
                      id="article_description"
                      disabled>
              <%= @article.description %>
            </textarea>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label" for="article_unit_category">Categorie d'unité</label>
          <div class="col-sm-9">
            <input class="form-control"
                   aria-required="true"
                   type="text"
                   id="article_unit_category"
                   value="<%= @article.articles_units.first.unit.unit_category.name %>"
                   disabled>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-3 control-label" for="articles_units_unit_id">Unité *</label>
          <div class="col-sm-9">
            <input class="form-control"
                   aria-required="true"
                   type="text"
                   id="articles_units_unit_id"
                   value="<%= @article.articles_units.first.unit.name %>"
                   disabled>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label" for="articles_units_value">Valeur *</label>
          <div class="col-sm-9">
            <input class="form-control"
                   aria-required="true"
                   type="text"
                   id="articles_units_value"
                   value="<%= @article.articles_units.first.value %>"
                   disabled>
          </div>
        </div>
      </div>


    </div>

    <a href="<%= edit_article_path %>" class="btn btn-primary">
      <span class="glyphicon glyphicon-edit" aria-hidden="true"> </span>
      Editer
    </a>
    <button class="btn-danger" data-toggle="modal" data-target="#delete">
      <span class="glyphicon glyphicon-remove" aria-hidden="true"> </span>
      Supprimer
    </button>

  </div>

</div>

<%= render 'articles_supplier', action: :show %>