config/routes.rb
Rails.application.routes.draw do

  # USERS & ADMINISTRATION
  devise_for :admins
  devise_for :users,
             :skip => [:registrations]
  as :user do
    get 'users/edit'  => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users'       => 'users/registrations#update', :as => 'user_registration'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # HOME
  root to: 'home#index'
  
  
  # RESSOURCES
  resources :commercials, path: 'commerciaux'
  resources :projects,    path: 'projets'
  resources :payments#,    path: 'paiement'
  resources :purchases,   path: 'achats'
  resources :suppliers,   path: 'fournisseurs'
  resources :customers,   path: 'clients'
  resources :orders,      path: 'commande'
  resources :quotes,      path: 'devis'
  resources :articles
  resources :order_items
  resources :units
  resources :conceptions, path: 'be'
  resources :house_modules, path: 'modules'
  resources :products, path: 'produits'

  get '/order/:order/item/new', to: 'order_items#new', as: 'new_order_item_supplier'

  # PAGE
  get '/pages/:id' => 'pages#show', as: 'page'

  # DESTROY LINKS
  resources :order_items, only: :destroy
  resources :articles_suppliers, only: :destroy

  # FROALA (WYSIWYG
  post '/froala_upload' => 'froala#upload'
  post '/froala_manage' => 'froala#manage'
  delete '/froala_delete' => 'froala#delete'
end

app/controllers/commercials_controller.rb
class CommercialsController < ApplicationController
  authorize_resource :class => false
  
  def index
    @last_quotes = Quote.order(updated_at: :desc).first(10)
    @last_projects = Project.order(updated_at: :desc).first(10)
  end
end

app/helpers/commercial_helper.rb
module CommercialHelper
  
  def get_params
    return "?#{@param_sort[:name]}=" if params[:page]==nil
    return "?#{@param_page[:name]}=#{@param_page[:value]}&#{@param_sort[:name]}=" if params[:page]!=nil
    return ''
  end
  
end

app/views/commercials/_lastprojects.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">Derniers Projets</h2>
  </div>
  
  <div class="panel-body">
    <table>
          <thead>
            <tr>
              <th>Num. projet</th>
              <th>Date</th>
              <th>Nom client</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
          <% @last_projects.each do |p| %>
            <tr>
              <td><%= p.id %></td>
              <td><%= format_date(p.created_at) %></td>
              <td><%= p.customer.fullname %></td>
              <td class="text-right">
                <%= link_to(raw('<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>'), p) %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
  </div>
</div>

app/views/commercials/_lastquotes.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">Derniers devis</h2>
  </div>
  
  <div class="panel-body">
    <table>
      <thead>
        <tr>
          <th><%= 'Num.' %></th>
          <th><%= 'Date MAJ' %></th>
          <th><%= 'Projet' %></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @last_quotes.each do |lq| %>
          <% p=Project.find(lq.project_id) %>
          <tr>
            <td><%= lq.id %></td>
            <td><%= format_date(lq.updated_at) %></td>
            <td><%= p.id %> | <%= Customer.find(p.id).fullname %></td>
            <td class="text-right">
              <%= link_to(raw('<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>'), lq) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/commercials/_menu.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    
    <div class="row">
      <div class="col-md-6">
        <%= link_to 'Créer projet', new_project_path, class: 'btn btn-primary' %>
      </div>
      <div class="row"><div class="col-md-6">
        <%= link_to 'Créer client', new_customer_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <div class="panel panel-default">
      <div class="panel-heading">Devis récents :</div>
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Num. projet</th>
              <th>Nom client</th>
            </tr>
          </thead>
          <tbody>
          <% @projects_menu.each do |p| %>
            <tr>
              <td><%= format_date(p.created_at) %></td>
              <td><%= link_to p.id, project_path(p.id) %></td>
              <td><%= p.customer.fullname %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>

app/views/commercials/index.html.erb
<% provide(:title, 'Commercial') %>
<% provide(:subtitle, 'Accueil') %>

<div class="row">
  
  <div class="col-md-3">
    <div class="thumbnail">
      <img src="<%= image_url('maison_madera.jpg') %>" alt="Maison Madera">
      <div class="caption">
        <h3>Maison Modulaire Madera</h3>
        <p>Les commerciaux doivent pouvoir réaliser au contact du client un devis prévisionnel en décrivant sur une tablette les caractéristiques de la maison modulaire souhaitée.</p>
        <%= link_to "Nouveau #{t('quote')}", new_quote_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>

  <div class="col-md-5">
    <%= render 'lastquotes' %>
  </div>
  
  <div class="col-md-4">
    <%= render 'lastprojects' %>
  </div>

</div>