config/routes.rb
Rails.application.routes.draw do

  # USERS & ADMINISTRATION
  devise_for :admins
  devise_for :users,
             :skip => [:registrations]
  as :user do
    get 'users/edit'  => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users'       => 'users/registrations#update', :as => 'user_registration'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # HOME
  root to: 'home#index'
  
  
  # RESSOURCES
  resources :commercials, path: 'commerciaux'
  resources :projects,    path: 'projets'
  resources :payments#,    path: 'paiement'
  resources :purchases,   path: 'achats'
  resources :suppliers,   path: 'fournisseurs'
  resources :customers,   path: 'clients'
  resources :orders,      path: 'commande'
  resources :quotes,      path: 'devis'
  resources :articles
  resources :order_items
  resources :units
  resources :conceptions, path: 'be'
  resources :house_modules, path: 'modules'
  resources :products, path: 'produits'

  get '/order/:order/item/new', to: 'order_items#new', as: 'new_order_item_supplier'

  # PAGE
  get '/pages/:id' => 'pages#show', as: 'page'

  # DESTROY LINKS
  resources :order_items, only: :destroy
  resources :articles_suppliers, only: :destroy

  # FROALA (WYSIWYG
  post '/froala_upload' => 'froala#upload'
  post '/froala_manage' => 'froala#manage'
  delete '/froala_delete' => 'froala#delete'
end

app/models/payment.rb
# == Schema Information
#
# Table name: payments
#
#  id               :integer          not null, primary key
#  quote_id         :integer
#  payment          :decimal(, )
#  payment_state_id :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Indexes
#
#  index_payments_on_payment_state_id  (payment_state_id)
#  index_payments_on_quote_id          (quote_id)
#

class Payment < ActiveRecord::Base

  belongs_to :quote
  belongs_to :payment_state

  validates_presence_of :quote, :payment, :payment_state
  validates_numericality_of :payment, greater_than: 0
  
  def to_label
    "#{name} : #{number_to_percentage(value*100, precision: 0)}"
  end
  
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  load_and_authorize_resource
  add_breadcrumb 'Paiement', :payments_path

  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.page(params[:page])
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Le paiement a été créé avec succès.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:quote_id, :payment, :payment_date, :payment_state_id)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= simple_form_for(@payment,  wrapper: :horizontal_form) do |f| %>
  <%= f.error_notification %>
  <div class="form-horizontal">
    <div class="form-inputs">
      <% disabled = (action == :show) ? true : false %>
      <%= f.association :quote, input_html: { disabled: disabled } %>
      <%= f.input :payment, input_html: { disabled: disabled } %>
      <%= f.association :payment_state, input_html: { disabled: disabled }  %>
    </div>

    <div class="form-actions">
      <% if action == :new %>
          <%= f.submit 'Créer' %>
      <% end %>
      <% if action == :edit %>
          <%= f.submit 'Mettre à jour' %>
      <% end %>
      <%= link_to('Retour', payments_path, class: 'btn btn-default pull-right') %>
    </div>
  </div>
<% end %>

app/views/payments/edit.html.erb
<% provide(:title, t('Payment')) %>
<% provide(:subtitle, 'Edition') %>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form', action: :edit %>
  </div>
</div>

app/views/payments/index.html.erb
<% provide(:title, t('payment')) %>
<% provide(:subtitle, 'Liste') %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title"><%= t 'listing payments' %></h2>
  </div>
  <div class="panel-body">
    <table>
      <thead>
        <tr>
              <th><%= t 'quote' %></th>
              <th><%= t 'payment' %></th>
              <th><%= t 'payment date' %></th>
              <th><%= t 'payment state' %></th>
              <th></th>
        </tr>
      </thead>

      <tbody>
        <% @payments.each do |payment| %>
          <tr>
                <td><%= link_to(payment.quote.to_label, quote_path(payment.quote)) %></td>
                <td><%= payment.payment %> €</td>
                <td><%= format_date(payment.updated_at) %></td>
                <td><%= payment.payment_state.name %></td>
                <td class="text-right">
              <%= link_to(
                raw('<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>'),
                payment
              )
              %>
              |
              <%= link_to(
                raw('<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>'),
                edit_payment_path(payment)
              )
              %>
              |
              <%= link_to(
                raw('<span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>'),
                payment,
                method: :delete, data: { confirm: 'Êtes vous certain ?' }
              ) %>

            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to t('Nouveau Paiement'), new_payment_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/payments/new.html.erb
<% provide(:title, t('Payment')) %>
<% provide(:subtitle, 'Création') %>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form', action: :new %>
  </div>
</div>

app/views/payments/show.html.erb
<% provide(:title, t('Payment')) %>
<% provide(:subtitle, 'Création') %>


<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="Effacer">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Êtes vous certain ?</h4>
      </div>
      <div class="modal-body">
        Êtes vous certain de vouloir effacer cet élément ?
      </div>
      <div class="modal-footer">
        <%= link_to 'Effacer',  @payment,  method: :delete, class: 'btn btn-danger' %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
      </div>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form', action: :show %>
    <a href="<%= edit_payment_path %>" class="btn btn-primary">
      <span class="glyphicon glyphicon-edit" aria-hidden="true"> </span>
      Editer
    </a>
    <button class="btn-danger" data-toggle="modal" data-target="#delete">
      <span class="glyphicon glyphicon-remove" aria-hidden="true"> </span>
      Supprimer
    </button>
  </div>
</div>